# Generated by Django 5.1.1 on 2024-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='alga_department',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alga_department',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alga_department',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
